### ISSUE TITLE
Is bio-knowledge-graph.n3 the knowledge graph used in the "Neuro-symbolic representation learning..." paper?

### ISSUE THREAD

**Issue by matthias-samwald** [bio-ontology-research-group/walking-rdf-and-owl#1]
Is this the dataset used in the paper?
It would certainly be interesting to create embeddings with other methodologies :)

**Comment by monaalsh** [comment]
yes, it is the dataset used in the paper. 
Thanks for your interest and please let me know if you need further information!

**Comment by abbynewbury** [comment]
What hyperparameters were used for training of these embeddings? I noticed in the paper, for example, it mentions that the embedding size of 512 was fixed throughout the experiment but the bio-knowledge-graph.n3 embeddings are of size 128. Thanks!
